fstring does not work with quotes in my python deployment (#32)
results in the following error message otherwise
```
E     File "/home/msperl/victron_mqtt/tests/static_hub_test.py", line 216
E       assert published['value'] == '{"value": 42}', f"Expected published value to be {'{"value": 42}'}, got {published['value']}"
E                                                                                          ^^^^^
E   SyntaxError: f-string: unterminated string
```

Why this happens only in one installation is unclear as of now (Debian 12.11 - Python 3.11.2)
But it is definitely a quoting issue - `\"` does not work either

Signed-off-by: Martin Sperl <martin@sperl.org>
Co-authored-by: Martin Sperl <martin@sperl.org>